# Welcome to Jekyll!

# Website settings
title: Prashant Shivaji Bhapkar
description: Prashant Shivaji Bhapkar
keywords: Prashant Shivaji Bhapkar
baseurl:
url: http://www.jarrekk.com
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author
author:
  name: Prashant Shivaji Bhapkar
  first_name: Prashant Shivaji
  last_name: Bhapkar
  cv: http://cv.jarrekk.com
  email: prashantbhpkr@gmail.com
  facebook_username: prashant.bhapkar.1
  github_username: PrashantShivajiBhapkar
  linkedin_id: prashant-shivaji-bhapkar-9b076623
  avatar: /static/assets/img/landing/Jack.jpeg
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc: I am a software engineer.

# comment
disqus:
  name: prashantshivajibhapkar-com

# analytics
## google analytics
ga:
  id: UA-111462392-1

go:
  id: 

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: off

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
